// Dados das travas e referência de perguntas
window.TRAVAS_DATA = [
  { nome: 'Ansiedade', descricao: 'Sinto que estou sempre preocupado com o futuro.' },
  { nome: 'Procrastinação', descricao: 'Deixo para depois o que poderia fazer agora.' },
  { nome: 'Culpa Excessiva', descricao: 'Sinto-me culpado por coisas que não são minha responsabilidade.' },
  { nome: 'Autossabotagem', descricao: 'Quando algo vai bem, acabo fazendo algo para estragar.' },
  { nome: 'Dificuldade de Dizer Não', descricao: 'Tenho dificuldade em recusar pedidos, mesmo quando me sobrecarrega.' },
  { nome: 'Medo de Cobrar', descricao: 'Evito cobrar o que é meu por direito.' },
  { nome: 'Baixa Autoconfiança', descricao: 'Não acredito que sou capaz de realizar grandes coisas.' },
  { nome: 'Perfeccionismo', descricao: 'Preciso que tudo seja perfeito, senão não vale a pena.' },
  { nome: 'Dependência Emocional', descricao: 'Preciso da aprovação dos outros para me sentir bem.' },
  { nome: 'Dificuldade com Críticas', descricao: 'Levo críticas como ataques pessoais.' }
];

window.DADOS_TESTE_REF = [
  { trava: 'TRAVA DA AUTOCONFIANÇA', perguntas: ['Evito situações desafiadoras: A pessoa pode se sentir incapaz de lidar com situações novas ou difíceis e evitar se envolver em atividades que a exijam.', 'Preocupação excessiva com a opinião dos outros: Uma pessoa pode se preocupar demais com o que os outros pensam e, assim, deixar de tomar decisões ou se expressar livremente.', 'Busca constante por aprovação: A pessoa pode ficar muito preocupada em agradar os outros e receber elogios, muitas vezes em detrimento de suas próprias necessidades.', 'Falta de iniciativa: A pessoa pode ter dificuldade em tomar a iniciativa para agir ou resolver problemas, esperando que outras pessoas assumam a liderança.', 'Baixa autoestima: A pessoa pode ter uma visão negativa de si mesma, subestimando suas capacidades e sentindo-se desanimada.'] },
  { trava: 'TRAVA DA ESCASSEZ', perguntas: ['Sentimento de falta constante: Uma pessoa pode sentir que nunca tem o suficiente, mesmo quando as necessidades básicas são atendidas, e pode viver em constante insatisfação.', 'Medo de perder: A pessoa pode ter medo de perder suas posses, recursos ou até mesmo seus relacionamentos e pode se sentir constantemente ameaçado pela possibilidade de perder o que tem.', 'Dificuldade em compartilhar: A pessoa pode ter dificuldade em compartilhar recursos ou tempo com outras pessoas, pois teme que isso possa levar-la a ter menos do que já tem.', 'Dificuldade em receber: A pessoa pode sentir-se desconfortável ao receber presentes, ajuda ou até mesmo elogios, pois acredita que não merece ou que não há nada de graça na vida.', 'Crença limitante: Uma pessoa pode acreditar que as oportunidades são limitadas e que é impossível ou muito dificil para ela ter mais ou melhorar sua situação.'] },
  { trava: 'TRAVA DA APROVAÇÃO', perguntas: ['Dificuldade em tomar decisões: A pessoa pode ter dificuldade em tomar decisões por si mesma, pois está sempre preocupada com o que os outros vão pensar ou como vão reagir.', 'Medo de julgamento: Uma pessoa pode ter medo de ser julgada ou rejeitada por outros e pode se sentir ansiosa ou insegura em relação à sua imagem.', 'Busca constante por aprovação: A pessoa pode se esforçar ao máximo para agradar aos outros e buscar sua aprovação, mesmo que isso signifique sacrificar suas próprias necessidades ou valores.', 'Baixa autoestima: A pessoa pode ter uma baixa autoestima e se sentir um pouco confiante em si mesma, confiando no reconhecimento e validação dos outros para se sentir bem consigo mesma.', 'Sentimento de insatisfação: A pessoa pode sentir-se insatisfeita mesmo quando recebe a aprovação dos outros, pois sente que nunca é o suficiente e continua buscando por mais.'] },
  { trava: 'TRAVA PATERNA', perguntas: ['Dificuldade em estabelecer um vínculo emocional com o pai ou figura paterna: A pessoa pode ter dificuldade em se conectar emocionalmente com seu pai, sentindo-se distante ou indiferente em relação a ele.', 'Sentimentos de ressentimento ou raiva em relação ao pai: A pessoa pode sentir ressentimento ou raiva em relação a seu pai devido a eventos do passado, como ausência, negligência, abuso ou outras formas de trauma.', 'Problemas de relacionamento: Uma pessoa pode ter dificuldade em estabelecer e manter relacionamentos saudáveis, pois pode sentir dificuldade em confiar ou se abrir emocionalmente devido à falta de um relacionamento próximo com o pai.', 'Comportamentos autodestrutivos: Uma pessoa pode ter comportamentos autodestrutivos, como abuso de substâncias, comportamento compulsivo ou relacionamentos abusivos, como uma forma de lidar com a dor e a falta de apoio paterno.', 'Dificuldade em estabelecer limites saudáveis: A pessoa pode ter dificuldade em estabelecer limites saudáveis em relacionamentos, pois pode ter dificuldade em reconhecer o que é saudável ou aceitável devido à falta de orientação e exemplo paterno.'] },
  { trava: 'TRAVA DA COMPETÊNCIA', perguntas: ['Dificuldade em aprender novos conceitos e informações, mesmo depois de tentar várias vezes;', 'Desinteresse ou falta de motivação em relação ao aprendizado;', 'Sensação de que a aprendizagem é difícil ou até mesmo impossível;', 'Baixa autoestima em relação às habilidades de aprendizado;', 'Dificuldade em manter a atenção durante as aulas ou durante a leitura;'] },
  { trava: 'TRAVA DA VÍTIMA', perguntas: ['Dificuldade em estabelecer limites e em dizer "não".', 'Tendência a seguir o que os outros dizem e se conformar com vontade alheia.', 'Dificuldade em lidar com conflitos e em se posicionar em situações de confronto.', 'Dificuldade em se importar e em defender seus interesses.', 'Tendência a EVITAR assumir responsabilidades.'] },
  { trava: 'TRAVA DA PERFEIÇÃO', perguntas: ['Dificuldade em concluir tarefas ou projetos por acreditar que eles nunca estão perfeitos o suficiente.', 'Ansiedade excessivamente em relação ao desempenho em todas as áreas da vida, incluindo trabalho, relacionamentos, estudos, etc.', 'Autocrítica constante e desaprovação interna, mesmo quanto os resultados alcançados são considerados bons por outras pessoas.', 'Rigidez em relação a regras e padrões, com dificuldade em lidar com mudanças e imprevistos.', 'Dificuldade em delegar tarefas para outras pessoas, devido à crença de que elas não eram capazes de realizá-las de forma satisfatória.'] },
  { trava: 'TRAVA DO SERVIDOR', perguntas: ['Ter dificuldade em dizer "não" para as demandas ou pedidos dos outros, mesmo que isso signifique sacrificar suas próprias necessidades e desejos.', 'Sentir-se frustrado ou ressentido com os outros por não reconhecerem ou conquistarem seus esforços e alcançarem em ajudá-los.', 'Sentir-se inseguro ou sem valor quando não é capaz de ajudar os outros.', 'Ter dificuldade em pedir ajuda ou apoio dos outros quando necessário, porque se sente culpado ou egoísta.', 'Sentir-se como se estivesse sempre "no modo de salvamento", colocando as necessidades dos outros acima de suas próprias necessidades e desejos.'] },
  { trava: 'TRAVA DA PROCRASTINAÇÃO', perguntas: ['Dificuldade para iniciar tarefas, mesmo aquelas que são importantes/urgentes;', 'Tendência a adiar tarefas, muitas vezes até o último minuto;', 'Sentimento de culpa por não conseguir cumprir suas responsabilidades dentro do prazo;', 'Dificuldade em manter o foco e a concentração durante o trabalho, o que pode levar a mais procrastinação;', 'Uso de distrações, como redes sociais, jogos ou outras atividades que não são produtivas, para evitar o trabalho;'] },
  { trava: 'TRAVA DO AMBIENTE', perguntas: ['Baixa autoestima: uma pessoa pode não acreditar em si mesma e pode ter medo de não encontrar um ambiente melhor;', 'Medo da mudança: a pessoa pode se sentir confortável com a situação atual, mesmo que seja tóxica, e pode ter medo de mudar para algo desconhecido;', 'Dependência emocional: a pessoa pode estar emocionalmente ligada às pessoas ou ao ambiente tóxico e pode achar difícil se afastar;', 'Falta de habilidades sociais: a pessoa pode não ter habilidades sociais adequadas para encontrar e estabelecer relações com pessoas saudáveis e, portanto, pode se sentir presa em ambientes acolhedores;', 'Medo da solidão: a pessoa pode ter medo de ficar sozinha e, portanto, pode preferir permanecer em um ambiente tóxico em vez de se afastar.'] }
];
